### ISSUE TITLE
Annoying Bars Above Tweet Container

### ISSUE THREAD

**Issue by devloop01** [jh3y/focussed-twitter#3]
The containers above the Tweet container creates annoying or bad looking bars. It will look better if you would remove it.

![Screenshot from 2019-10-28 11-20-42](https://user-images.githubusercontent.com/38714423/67699572-5bcb2880-f9d2-11e9-9310-c3f937c707cd.png)

**Comment by jh3y** [comment]
I've pushed the changes for this in v0.7. Will push up this version once the latest hopefully passes review 🤞  Then that one will need to pass review too.
